# The task layer: the single implementation site for every repeatable piece of
# automation in this repository. Local development, git hooks
# (.pre-commit-config.yaml) and CI (.github/workflows/) are all just callers.
# Rules: no version numbers here (reference the SSOT of the layer below); no
# bashisms or duplicated arguments in recipes — each tool's parameters live in
# that tool's own config file.

set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

export RUSTDOCFLAGS := "-D warnings"

# List all commands (just --list is living documentation)
default:
    @just --list

# Manual hook install for non-Nix shells — inside the devShell this happens
# automatically on entry (git cannot ship hooks with a clone)
setup:
    prek install --hook-type pre-commit --hook-type commit-msg

# In CI the pre-commit framework fails the job if files were modified by this
# (see the quality-gate job), so the check-mode twin is only exercised there.

# Format all Rust code (write mode)
fmt:
    cargo fmt --all

# The two ignored shellcheck codes are style hints from the dist-generated
# release.yml, which we must not hand-edit (drift check); accepted policy.
# No path argument: actionlint discovers .github/workflows/ itself, because
# the Windows shell (PowerShell) does not expand globs for native commands.

# Static checks: rustfmt --check, clippy (-D warnings), actionlint on workflow YAML
lint:
    cargo fmt --all -- --check
    cargo clippy --workspace --all-targets -- -D warnings
    actionlint -ignore 'SC2086' -ignore 'SC2129'

# Tests: nextest (process isolation) + doctests (README/rustdoc examples are compiled too)
test:
    cargo nextest run --workspace --all-targets
    cargo test --doc --workspace

# Build docs (rustdoc warnings are errors; RUSTDOCFLAGS injected at the top of this file)
doc:
    cargo doc --no-deps --workspace

# Dependency policy: advisories / licenses / duplicate versions / sources (see deny.toml)
deny:
    cargo deny check

# .github/workflows/release.yml is generated by `dist generate` — never
# hand-edit it; this recipe is the drift check (also a CI job).

# Drift check: fail if generated release.yml diverges from dist-workspace.toml
dist-check:
    dist generate --mode ci --check

# Snapshot review: approve diffs one by one; CI is read-only and never auto-accepts
snapshot-review:
    cargo insta review

# Smoke check for agent-facing docs: SKILL.md frontmatter, size budgets, and
# pointer integrity (AGENTS.md / CLAUDE.md / .claude/skills). Std-only Rust in
# crates/xtask; runs on every platform `just ci` runs on.
agent-check:
    cargo run -q -p xtask -- agent-check

# The local full quality gate ≡ CI (modulo matrix dimensions); run before committing
ci: lint test doc deny agent-check
    @echo "just ci: all green ✅"

# Add an internal crate (unpublished by default; rules in CONTRIBUTING.md "Adding a crate")
new-crate name:
    cargo run -q -p xtask -- new-crate {{name}}

# >>> template-only: bootstrap entry; removed by a successful init

# Turn the template into a fresh project (rename, strip template artifacts, git init)
init name owner:
    cargo run -q -p xtask -- init {{name}} {{owner}}
# <<< template-only
